name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v3

      - name: Собрать Docker образ
        run: docker build -t lab-app .

      - name: Запустить контейнер
        run: docker run -d -p 8000:8000 lab-app

      - name: Проверка сервиса
        run: |
          sleep 5
          curl http://localhost:8000
